# GitHub Pages Clean URLs Configuration

# For GitHub Pages, create duplicate files without .html extension
# This is a workaround since GitHub Pages doesn't support .htaccess

# File structure needed:
# /calendar (copy of calendar.html)
# /dashboard (copy of dashboard.html)
# /units (copy of units.html)
# /contacts (copy of contacts.html)
# /website (copy of website.html)
# /aiagent (copy of aiagent.html)

# Alternative: Use Jekyll for GitHub Pages (recommended)
# Create _config.yml:

plugins:
  - jekyll-redirect-from

# URL settings
permalink: pretty

# This will automatically handle clean URLs